export const SET_GRIDSIZE = 'SET_GRIDSIZE';
export const ADD_COLUMN = 'ADD_COLUMN'
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER'
export const MODIFY_BOARD_MAP = 'MODIFY_BOARD_MAP'
export const SET_WINNER = 'SET_WINNER'
export const RESET_GAME = 'RESET_GAME'
export const IS_AGAINST_ALG = 'IS_AGAINST_ALG'
